/*
 * ModemConfigFile.cpp - where the modem's direwolf.conf lives.
 *
 * This file is part of AX25Chess.
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include "ModemConfigFile.h"
#include "RadioConfig.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>
#include <QStandardPaths>
#include <QTemporaryFile>
#include <QRegularExpression>
#include <QTextStream>

namespace modemconf {

QString userPath()
{
    return QDir(RadioConfig::configDir()).filePath(QStringLiteral("direwolf.conf"));
}

bool directoryIsWritable(const QString &directory)
{
    if (!QFileInfo(directory).isDir()) return false;
    QTemporaryFile probe(QDir(directory).filePath(QStringLiteral(".ax25chess-XXXXXX")));
    return probe.open();
}

QString writeStarter(const QString &pathIn, const QString &callsign, QString *error)
{
    QString path = pathIn;
    if (QFileInfo::exists(path)) return path;

    QString directory = QFileInfo(path).absolutePath();
    if (!directoryIsWritable(directory)) {
        QDir().mkpath(directory);
        if (!directoryIsWritable(directory)) {
            path = userPath();
            directory = QFileInfo(path).absolutePath();
        }
    }
    if (!QDir().mkpath(directory)) {
        if (error) *error = QStringLiteral("Cannot create %1").arg(directory);
        return QString();
    }

#ifdef Q_OS_WIN
    const QString ptt = QStringLiteral("#PTT      COM3 RTS");
#else
    const QString ptt = QStringLiteral("#PTT      /dev/ttyUSB0 RTS");
#endif
    const QString text = QStringLiteral(
        "# direwolf.conf written by AX25Chess for you to edit.\n"
        "# Full reference: the User Guide shipped with Dire Wolf.\n"
        "\n"
        "# Audio device. 0 is the first one; on Linux \"plughw:1,0\" style names work too.\n"
        "ADEVICE  0\n"
        "CHANNEL  0\n"
        "MYCALL   %1\n"
        "\n"
        "# 1200 baud AFSK is standard on VHF packet and APRS.\n"
        "MODEM    1200\n"
        "\n"
        "# Transmit keying. VOX adds a release delay that collides with the next\n"
        "# station, so a real PTT line is strongly preferred on packet.\n"
        "%2\n").arg(callsign.isEmpty() ? QStringLiteral("NOCALL") : callsign, ptt);

    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        if (error) *error = file.errorString();
        return QString();
    }
    file.write(text.toUtf8());
    if (!file.commit()) {
        if (error) *error = file.errorString();
        return QString();
    }
    return path;
}

QString defaultSerialPort()
{
#ifdef Q_OS_WIN
    return QStringLiteral("COM3");
#else
    return QStringLiteral("/dev/ttyUSB0");
#endif
}

QString generatedText(const QString &callsign, const ModemConfig &m)
{
    QString pttLine;
    const QString serial = m.pttDevice.isEmpty() ? defaultSerialPort() : m.pttDevice;
    if (m.ptt == QLatin1String("cm108")) {
        pttLine = QStringLiteral("PTT      CM108 %1").arg(m.gpio);
        if (!m.pttDevice.isEmpty()) pttLine += QLatin1Char(' ') + m.pttDevice;
    } else if (m.ptt == QLatin1String("rts")) {
        pttLine = QStringLiteral("PTT      %1 RTS").arg(serial);
    } else if (m.ptt == QLatin1String("dtr")) {
        pttLine = QStringLiteral("PTT      %1 DTR").arg(serial);
    } else {
        pttLine = QStringLiteral("# No PTT line: the radio's VOX keys the transmitter.");
    }
    const QString in = m.audioIn.isEmpty() ? QStringLiteral("default") : m.audioIn;
    const QString out = m.audioOut.isEmpty() ? in : m.audioOut;
    // Both on the system default: no ADEVICE line at all, which is Dire
    // Wolf's own default on every platform (Windows would otherwise look for
    // a device named "default" and complain that none matches).
    const QString adevice = (in == QLatin1String("default") && out == QLatin1String("default"))
        ? QStringLiteral("#ADEVICE default      (the system default device)")
        : QStringLiteral("ADEVICE  ") + (in == out ? in : in + QLatin1Char(' ') + out);

    return QStringLiteral(
        "# direwolf.conf generated by AX25Chess from Settings -> Modem.\n"
        "# Rewritten every time the settings are saved: change them there, or\n"
        "# choose \"My own direwolf.conf\" to keep a file of your own.\n"
        "\n"
        "%1\n"
        "ARATE    %2\n"
        "CHANNEL  %3\n"
        "MYCALL   %4\n"
        "MODEM    %5\n"
        "%6\n"
        "\n"
        "# Channel access, in units of 10 ms except PERSIST (0-255).\n"
        "TXDELAY  %7\n"
        "TXTAIL   %8\n"
        "PERSIST  %9\n"
        "SLOTTIME %10\n"
        "FULLDUP  %11\n")
        .arg(adevice)
        .arg(m.sampleRate)
        .arg(m.channel)
        .arg(callsign.isEmpty() ? QStringLiteral("NOCALL") : callsign.toUpper())
        .arg(m.speed)
        .arg(pttLine)
        .arg(m.txdelay)
        .arg(m.txtail)
        .arg(m.persistence)
        .arg(m.slottime)
        .arg(m.fullDuplex ? QStringLiteral("ON") : QStringLiteral("OFF"));
}

QString writeGenerated(const QString &path, const QString &callsign, const ModemConfig &modem, QString *error)
{
    const QString directory = QFileInfo(path).absolutePath();
    if (!QDir().mkpath(directory)) {
        if (error) *error = QStringLiteral("Cannot create %1").arg(directory);
        return QString();
    }
    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        if (error) *error = file.errorString();
        return QString();
    }
    file.write(generatedText(callsign, modem).toUtf8());
    if (!file.commit()) {
        if (error) *error = file.errorString();
        return QString();
    }
    return path;
}

QString defaultFile()
{
    QStringList candidates;
#ifdef Q_OS_WIN
    candidates << QDir::home().filePath(QStringLiteral("direwolf.conf"));
#endif
    candidates << userPath()
               << QDir::home().filePath(QStringLiteral("direwolf.conf"))
               << QDir::home().filePath(QStringLiteral(".direwolf/direwolf.conf"))
               << QStringLiteral("/etc/direwolf.conf");
#ifdef Q_OS_WIN
    candidates << QStringLiteral("C:\\Program Files\\Direwolf\\direwolf.conf");
#endif
    for (const QString &path : candidates) {
        if (QFileInfo(path).isFile()) return path;
    }
    return QString();
}

QList<int> channelsIn(const QString &path)
{
    QList<int> channels;
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) return channels;
    QTextStream in(&file);
    while (!in.atEnd()) {
        const QString line = in.readLine().trimmed();
        if (line.startsWith('#')) continue;
        const QStringList words = line.split(QRegularExpression(QStringLiteral("\\s+")), Qt::SkipEmptyParts);
        if (words.size() >= 2 && words.at(0).compare(QStringLiteral("CHANNEL"), Qt::CaseInsensitive) == 0) {
            bool ok = false;
            const int n = words.at(1).toInt(&ok);
            if (ok && !channels.contains(n)) channels << n;
        }
    }
    return channels;
}

} // namespace modemconf
